BulkyWeb/Areas/Admin/Controllers/CategoryController.cs
using BulkyBook.DataAccess.Repository.IRepository;
using BulkyBook.DataAccess.Data;
using BulkyBook.Models;
using Microsoft.AspNetCore.Mvc;
using BulkyBook.Utility;
using Microsoft.AspNetCore.Authorization;

namespace BulkyBookWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
	//[Authorize(Roles = SD.Role_Admin)]
	public class CategoryController : Controller
    {
        private readonly IUnitOfWork _uow;

        public CategoryController(IUnitOfWork uow)
        {
            _uow = uow;

        }
        public IActionResult Index()
        {
            List<Category> objCategoryList = _uow.Category.GetAll().ToList();
            return View(objCategoryList);
        }

        public IActionResult Create()
        {
            Category ctg = new Category();
            ctg = null;
            return View("Create", ctg);
        }

        [HttpPost]
        public IActionResult Create(Category obj)
        {
            //if (obj.Name == obj.DisplayOrder.ToString())
            //{
            //	ModelState.AddModelError("name", "The display order can not exactly match the name.");
            //}
            if (ModelState.IsValid)
            {
                _uow.Category.Add(obj);
                _uow.Save();
                TempData["success"] = "Category Created Successfully";
                return RedirectToAction("Index");
            }
            return View();

        }

        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            Category? categoryFromDb = _uow.Category.Get(u => u.Id == id);
            if (categoryFromDb == null)
            {
                return NotFound();
            }
            return View("Create", categoryFromDb);
        }

        [HttpPost]
        public IActionResult Edit(Category obj)
        {
            _uow.Category.Update(obj);
            _uow.Save();
            TempData["success"] = "Category Updated Successfuly!";
            return RedirectToAction("Index");
        }


        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            Category? categoryItemToBeDeleted = _uow.Category.Get(u => u.Id == id);
            if (categoryItemToBeDeleted == null)
            {
                return NotFound();
            }
            _uow.Category.Remove(categoryItemToBeDeleted);
            _uow.Save();
            TempData["success"] = "Category deleted successfully";
            return RedirectToAction("Index");
        }



    }


}

BulkyWeb/Areas/Admin/Controllers/CompanyController.cs
using BulkyBook.DataAccess.Repository.IRepository;
using BulkyBook.Models;
using BulkyBook.Models.ViewModels;
using BulkyBook.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace BulkyBookWeb.Areas.Admin.Controllers
{
	[Area("Admin")]
	//[Authorize(Roles =SD.Role_Admin)]
	public class CompanyController : Controller
	{
		public readonly IUnitOfWork _uow;
		public readonly IWebHostEnvironment _webHostEnvironment;
		public CompanyController(IUnitOfWork uow , IWebHostEnvironment webHostEnvironment)
		{
			_uow = uow;
			_webHostEnvironment = webHostEnvironment;
		}
		public IActionResult Index()
		{
			List<Company> companyObj = _uow.Company.GetAll().ToList();
			return View(companyObj);
		}

		public IActionResult UpdateInsert(int? id)
		{//ViewBag.CategoryListDropdownItem = CategoryList;
			
			if (id == 0 || id == null)
			{
				return View(new Company());//create
			}
			else{
                Company companyObj = _uow.Company.Get(u=>u.Id==id);//update
				return View(companyObj);
			}
		}
		
		[HttpPost]
		public IActionResult UpdateInsert(Company companyObj)
		{
			if (ModelState.IsValid)
			{
				string wwwRootPath = _webHostEnvironment.WebRootPath;
				if(companyObj.Id == 0 || companyObj.Id == null){
					//create kro bhayiii
					_uow.Company.Add(companyObj);
					_uow.Save();
					TempData["success"] = " Product Created Successfully!";
				}
				else{
					//Update kro  
					_uow.Company.Update(companyObj);
					_uow.Save();
					TempData["success"] = " Product Updated Successfully!";
				}
				return RedirectToAction("Index");
			}
			else
			{
				return View(companyObj);
			}

		}
		  
		


		#region API CALLS
		[HttpGet]
		public IActionResult GetAll(int id) {
			List<Company> companytObj = _uow.Company.GetAll().ToList();
			return Json(new { data = companytObj });
		}

		[HttpDelete]
		public IActionResult Delete(int? id)
		{

			var productToBeDeleted = _uow.Company.Get(u => u.Id == id);
			if (productToBeDeleted == null)
			{
				return Json(new {success = false , message = "Error while Deleting"});
			}
			
			_uow.Company.Remove(productToBeDeleted);
			_uow.Save();
			//TempData["success"] = " Product Deleted Successfully!";
			return Json(new { success = true, message = "Delete Successfully!" });
		}
		#endregion
	}
}

BulkyWeb/Areas/Admin/Controllers/OrderController.cs
using System.Diagnostics;
using System.Security.Claims;
using Braintree;
using BulkyBook.DataAccess.Repository.IRepository;
using BulkyBook.Models;
using BulkyBook.Models.ViewModels;
using BulkyBook.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;

namespace BulkyBookWeb.Areas.Admin.Controllers
{
	[Area("Admin")]
	public class OrderController : Controller
    {
      
      
        public readonly IUnitOfWork _uow;

        [BindProperty]
        public OrderVM OrderVM { get; set; }
        public readonly IWebHostEnvironment _webHostEnvironment;

        public OrderController(IUnitOfWork uow, IWebHostEnvironment webHostEnvironment)
        {
            _uow = uow;
            _webHostEnvironment = webHostEnvironment;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Details(int orderId) {
            OrderVM  = new()
            {
                OrderHeader = _uow.OrderHeader.Get(u => u.Id == orderId, includeProperties: "ApplicationUser"),
                OrderDetail = _uow.OrderDetails.GetAll(u => u.OrderHeaderId == orderId, includeProperties: "Product")
            };
            return View(OrderVM);
        }


        [HttpPost]
        [Authorize(Roles = SD.Role_Admin+ ","+SD.Role_Employee)]
        public IActionResult UpdateOrderDetail()
        {
            var orderHeaderFromDb = _uow.OrderHeader.Get(u => u.Id == OrderVM.OrderHeader.Id);
            orderHeaderFromDb.Name = OrderVM.OrderHeader.Name;
            orderHeaderFromDb.PhoneNumber = OrderVM.OrderHeader.PhoneNumber;
            orderHeaderFromDb.StreetAddress = OrderVM.OrderHeader.StreetAddress;
            orderHeaderFromDb.City = OrderVM.OrderHeader.City;
            orderHeaderFromDb.State = OrderVM.OrderHeader.State;
            orderHeaderFromDb.PostalCode = OrderVM.OrderHeader.PostalCode;
            if(!string.IsNullOrEmpty(OrderVM.OrderHeader.Carrier)){
                orderHeaderFromDb.Carrier = OrderVM.OrderHeader.Carrier;
            }
            if (!string.IsNullOrEmpty(OrderVM.OrderHeader.TrackingNumber))
            {
                orderHeaderFromDb.Carrier = OrderVM.OrderHeader.TrackingNumber;
            }
            _uow.OrderHeader.Update(orderHeaderFromDb);
            _uow.Save();
            TempData["Success"] = "Order Detail Updated Successfully !";
            return RedirectToAction(nameof(Details), new { orderId = orderHeaderFromDb.Id });
        }
        #region API CALLS
        [HttpGet]
        public IActionResult GetAll(string status)
        {
            IEnumerable<OrderHeader> orderHeaderObj ;
            if(User.IsInRole(SD.Role_Admin) || User.IsInRole(SD.Role_Employee)){
                orderHeaderObj = _uow.OrderHeader.GetAll(includeProperties:"ApplicationUser").ToList();
            }
            else{
                var claimsIdentity = (ClaimsIdentity)User.Identity;
                var userId = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier).Value;
                orderHeaderObj = _uow.OrderHeader.GetAll(u=>u.ApplicationUserId == userId , includeProperties: "ApplicationUser");
            }
            

			switch (status)
			{
				case "inprocess":
					orderHeaderObj = orderHeaderObj.Where(u=> u.OrderStatus == SD.StatusInProcess).ToList();
					break;
				case "pending":
					orderHeaderObj = orderHeaderObj.Where(u => u.PaymentStatus == SD.PaymentStatusPending).ToList();
					break;
				case "completed":
					orderHeaderObj = orderHeaderObj.Where(u=> u.OrderStatus == SD.StatusShipped).ToList();
					break;
				case "approved":
					orderHeaderObj = orderHeaderObj.Where(u => u.OrderStatus == SD.StatusApproved).ToList(); ;
					break;
				default:
					break;

			}

			return Json(new { data = orderHeaderObj });
        }

        [HttpDelete]
        public IActionResult Delete(int? id)
        {

            var productToBeDeleted = _uow.Product.Get(u => u.Id == id);
            if (productToBeDeleted == null)
            {
                return Json(new { success = false, message = "Error while Deleting" });
            }
            var oldImgPath = Path.Combine(_webHostEnvironment.WebRootPath, productToBeDeleted.
            ImgUrl.TrimStart('\\'));
            if (System.IO.File.Exists(oldImgPath))
            {
                System.IO.File.Delete(oldImgPath);
            }
            _uow.Product.Remove(productToBeDeleted);
            _uow.Save();
            //TempData["success"] = " Product Deleted Successfully!";
            return Json(new { success = true, message = "Delete Successfully!" });
        }
        #endregion
    }
}

BulkyWeb/Areas/Customer/Controllers/CartController.cs
using System.Security.Claims;
using BulkyBook.DataAccess.Repository;
using BulkyBook.DataAccess.Repository.IRepository;
using BulkyBook.Models;
using BulkyBook.Models.ViewModels;
using BulkyBook.Utility;
using Microsoft.AspNetCore.Mvc;

namespace BulkyBookWeb.Areas.Customer.Controllers
{
	[Area("customer")]
	public class CartController : Controller
	{
		private readonly IUnitOfWork _uow;

		[BindProperty]
		public ShoppingCartVM ShoppingCartVM { get; set; }
		public CartController(IUnitOfWork uow)
		{
			_uow = uow;
		}
		public IActionResult Index()
		{
			var claimIdentity = (ClaimsIdentity)User.Identity;
			var userId = claimIdentity.FindFirst(ClaimTypes.NameIdentifier).Value;
			ShoppingCartVM = new()
			{
				ShoppingCartlist = _uow.ShoppingCart.GetAll(u => u.ApplicationUserId == userId, includeProperties: "Product"),
				OrderHeader = new()
			};

			foreach (var cart in ShoppingCartVM.ShoppingCartlist)
			{
				cart.Price = GetPriceBasedOnQuantity(cart);
				ShoppingCartVM.OrderHeader.OrderTotal += (cart.Price * cart.Count);
			}
			return View(ShoppingCartVM);
		}

		public IActionResult Plus(int id)
		{
			var itemToBeIncremented = _uow.ShoppingCart.Get(x => x.Id == id);
			itemToBeIncremented.Count += 1;
			_uow.ShoppingCart.Update(itemToBeIncremented);
			_uow.Save();
			return RedirectToAction(nameof(Index));
		}
		public IActionResult Minus(int id)
		{
			var itemToBeDecremented = _uow.ShoppingCart.Get(x => x.Id == id);
			if (itemToBeDecremented.Count == 1)
			{
				_uow.ShoppingCart.Remove(itemToBeDecremented);
			}
			else
			{
				itemToBeDecremented.Count -= 1;
				_uow.ShoppingCart.Update(itemToBeDecremented);
			}
			_uow.Save();
			return RedirectToAction(nameof(Index));
		}

		public IActionResult Remove(int id)
		{
			var itemToBeDeleted = _uow.ShoppingCart.Get(x => x.Id == id);
			_uow.ShoppingCart.Remove(itemToBeDeleted);
			_uow.Save();
			return RedirectToAction(nameof(Index));
		}

		public IActionResult Summary()
		{
			var claimIdentity = (ClaimsIdentity)User.Identity;
			var userId = claimIdentity.FindFirst(ClaimTypes.NameIdentifier).Value;
			ShoppingCartVM = new()
			{
				ShoppingCartlist = _uow.ShoppingCart.GetAll(u => u.ApplicationUserId == userId, includeProperties: "Product"),
				OrderHeader = new()
			};

			ShoppingCartVM.OrderHeader.ApplicationUser = _uow.ApplicationUser.Get(u => u.Id == userId);

			ShoppingCartVM.OrderHeader.Name = ShoppingCartVM.OrderHeader.ApplicationUser.Name;
			ShoppingCartVM.OrderHeader.PhoneNumber = ShoppingCartVM.OrderHeader.ApplicationUser.PhoneNumber;
			ShoppingCartVM.OrderHeader.StreetAddress =ShoppingCartVM.OrderHeader.ApplicationUser.StreetAdress;
			ShoppingCartVM.OrderHeader.City = ShoppingCartVM.OrderHeader.ApplicationUser.City;
			ShoppingCartVM.OrderHeader.State = ShoppingCartVM.OrderHeader.ApplicationUser.State;
			ShoppingCartVM.OrderHeader.PostalCode = ShoppingCartVM.OrderHeader.ApplicationUser.PostalCode;
			foreach (var cart in ShoppingCartVM.ShoppingCartlist)
			{
				cart.Price = GetPriceBasedOnQuantity(cart);
				ShoppingCartVM.OrderHeader.OrderTotal += (cart.Price * cart.Count);
			}
			return View(ShoppingCartVM);
		}
		
		[HttpPost]
		[ActionName("Summary")]
		public IActionResult SummaryPost()
		{
			var claimIdentity = (ClaimsIdentity)User.Identity;
			var userId = claimIdentity.FindFirst(ClaimTypes.NameIdentifier).Value;
			ShoppingCartVM.ShoppingCartlist = _uow.ShoppingCart.GetAll(u => u.ApplicationUserId == userId, includeProperties: "Product");
			ShoppingCartVM.OrderHeader.OrderDate = System.DateTime.Now;
			ShoppingCartVM.OrderHeader.ApplicationUserId = userId;
		

		ApplicationUser applicationUser = _uow.ApplicationUser.Get(u => u.Id == userId);

			foreach (var cart in ShoppingCartVM.ShoppingCartlist)
			{
				cart.Price = GetPriceBasedOnQuantity(cart);
				ShoppingCartVM.OrderHeader.OrderTotal += (cart.Price * cart.Count);
			}

			if(applicationUser.ComapnyId.GetValueOrDefault()==0){
				//it is regular customer account & we need to capture the payment
				ShoppingCartVM.OrderHeader.PaymentStatus = SD.PaymentStatusPending;
				ShoppingCartVM.OrderHeader.OrderStatus = SD.StatusPending;
			}
			else{
				//it is a company user 
				ShoppingCartVM.OrderHeader.PaymentStatus = SD.PaymentStatusDelayedPayment;
				ShoppingCartVM.OrderHeader.OrderStatus = SD.StatusApproved;
			}
			_uow.OrderHeader.Add(ShoppingCartVM.OrderHeader);
			_uow.Save();

			//create order detail 
			foreach(var cart in ShoppingCartVM.ShoppingCartlist){
				OrderDetails orderDetail = new()
				{
					ProductId = cart.ProductId,
					OrderHeaderId = ShoppingCartVM.OrderHeader.Id,
					Price = cart.Price,
					Count = cart.Count
				};
			_uow.OrderDetails.Add(orderDetail);
			_uow.Save();	
			}

			if (applicationUser.ComapnyId.GetValueOrDefault() == 0)
			{
				//it is regular customer account & we need to capture the payment
				//brain tree logic here
			}
            string url = string.Format("/Admin/BrainTree" , ShoppingCartVM.OrderHeader.OrderTotal);
            int totalAmount = Convert.ToInt32(ShoppingCartVM.OrderHeader.OrderTotal);
            TempData["totalAmount"] = totalAmount;

            return Redirect(url);
		}

		public IActionResult OrderConfirmation(int id){
			return View();
		}
		
		private double GetPriceBasedOnQuantity(ShoppingCart shoppingCart)
		{
			if (shoppingCart.Count <= 50)
			{
				return shoppingCart.Product.Price;
			}
			else if (shoppingCart.Count <= 100)
			{
				return shoppingCart.Product.Price50;
			}
			else
			{
				return shoppingCart.Product.Price100;
			}
		}


	}
}

BulkyWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - BulkyBookWeb</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
	<script src="https://cdn.tiny.cloud/1/mph881xfcewxbsq97fgt6431n22l92iib7eq80pksdu740ab/tinymce/7/tinymce.min.js" referrerpolicy="origin"></script>

	<link rel="stylesheet" href="~/BulkyBookWeb.styles.css" asp-append-version="true" />
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	<link rel="stylesheet" href="//cdn.datatables.net/2.0.8/css/dataTables.dataTables.min.css" />
</head>
<body>
	<header>
		<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary border-bottom box-shadow mb-3">
			<div class="container-fluid">
				<a class="navbar-brand" asp-area="Customer" asp-controller="Home" asp-action="Index">BulkyBookWeb</a>
				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
						aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
					<ul class="navbar-nav me-auto">
						<li class="nav-item">
							<a class="nav-link " asp-area="Customer" asp-controller="Home" asp-action="Index">Home</a>
						</li>
						<li class="nav-item">
							<a class="nav-link " asp-area="Admin" asp-controller="Order" asp-action="Index">Manage Order</a>
						</li>
						<li class="nav-item">
							<a class="nav-link " asp-area="Admin" asp-controller="BrainTree" asp-action="Index">BrainTree</a>
						</li>

						  @if (User.IsInRole(SD.Role_Admin))
						{
							<li class="nav-item dropdown">
								<a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown">
									Category Management
								</a>
								<ul class="dropdown-menu">
									<li class="nav-item">
										<a class="dropdown-item" asp-area="Admin" asp-controller="Category" asp-action="Index">Category</a>
									</li>
									<li class="nav-item">
										<a class="dropdown-item" asp-area="Admin" asp-controller="Product" asp-action="Index">Product</a>
									</li>
									<li class="nav-item">
										<a class="dropdown-item" asp-area="Admin" asp-controller="Company" asp-action="Index">Company</a>
									</li>
								</ul>
							</li>

						}
						<li class="nav-item">
							<a class="nav-link " asp-area="Customer" asp-controller="Cart" asp-action="Index"><i class="bi bi-cart"></i>&nbsp; (0)</a>
						</li>
					</ul>
					<partial name="_LoginPartial" />
				</div>
			</div>
		</nav>
	</header>
	<div class="container">
		<main role="main" class="pb-3">
			<partial name="_Notification" />
			@RenderBody()
		</main>
	</div>

	<footer class="border-top footer bg-primary text-muted">
		<div class="container text-center">
			Made with <i class="bi bi-balloon-heart"></i> by Shivi
		</div>
	</footer>
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
	<script src="//cdn.datatables.net/2.0.8/js/dataTables.min.js" asp-append-version="true"></script>
	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

BulkyWeb/Views/Shared/_Notification.cshtml
@if (TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]');
    </script>
}
@if (TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["error"]');
    </script>
}